---
authors:
- admin
categories: []
date: "2019-08-05T00:00:00Z"
draft: false
featured: false
image:
  caption: ""
  focal_point: ""
projects: []
subtitle: regular-expression
summary: 
tags: []
title: regular-expression
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

字元分類      | 表示
--------------|------------------------
\\d           | 0-9的任何數字
\\D           | 除了0-9的任何數字
\\w           | 任何字母,數字或底線
\\W           | 除了字母,數字或底線以外的任何字元
\\s           | 空格,定位符號或換行符號
\\S           | 除了空格,定位符號或換行符號以外的任何字元



<div class="book">
<ul class="itemizedlist">
<li class="listitem">
<p class="calibre4">The <code class="literal1">?</code> matches zero or one of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">*</code> matches zero or more of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">+</code> matches one or more of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">{n}</code> matches exactly <span class="calibre1"><em class="calibre5">n</em></span> of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">{n,}</code> matches <span class="calibre1"><em class="calibre5">n</em></span> or more of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">{,m}</code> matches 0 to <span class="calibre1"><em class="calibre5">m</em></span> of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">{n,m}</code> matches at least <span class="calibre1"><em class="calibre5">n</em></span> and at most <span class="calibre1"><em class="calibre5">m</em></span> of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4"><code class="literal1">{n,m}?</code> or <code class="literal1">*?</code> or <code class="literal1">+?</code> performs a nongreedy match of the preceding group.</p>
</li>
<li class="listitem">
<p class="calibre4"><code class="literal1">^spam</code> means the string must begin with <span class="calibre1"><em class="calibre5">spam</em></span>.</p>
</li>
<li class="listitem">
<p class="calibre4"><code class="literal1">spam$</code> means the string must end with <span class="calibre1"><em class="calibre5">spam</em></span>.</p>
</li>
<li class="listitem">
<p class="calibre4">The <code class="literal1">.</code> matches any character, except newline characters.</p>
</li>
</ul>
</div>

+  \\d, \\w, and \\s match a digit, word, or space character, respectively.

+  \\D, \\W, and \\S match anything except a digit, word, or space character, respectively.

+  [abc] matches any character between the brackets (such as a, b, or c).

+  [^abc] matches any character that isn’t between the brackets.

### python 正規表達式 都在re模組

1. import re
2. re.complie() 建立 Regex物件 (記得使用原始字串 (r))
3. 對 Regex 物件的 search() 方法傳入想要尋找的字串,會返回一個Match物件
4. 呼叫Match物件的group()方法,返回實際比對符合的字串
```{python}
import re

phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo = phoneNumRegex.search('My number is 415-555-4242.')
print('Phone number found: ' + mo.group())
```

我們想要把區域號碼從電話號碼中分開,可在正規表達式中加上括號來分組:

`(\d\d\d)-(\d\d\d-\d\d\d\d)`

隨後使用 group() 方法從某個分組中取得比對符合的文字
```{python}
phoneNumRegex = re.compile(r'(\d\d\d)-(\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('My number is 415-555-4242.')
mo.group(1)
mo.group(2)

mo.group(0)

mo.group()
```
想要一次取得所有的分組,可用groups()方法

```{python}
mo.groups()
areaCode,mainNumber = mo.groups()
print(areaCode)
print(mainNumber)
```

想要在字串中比對括號,使用`\(` 和 `\)`

在傳入 re.compile()的原始字串內的`\(` 和 `\)`會變得實際比對()括號

```{python}
phoneNumRegex = re.compile(r'(\(\d\d\d\)) (\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('My phone number is (415) 555-4242.')
mo.group(1)

mo.group(2)
```

####Matching Multiple Groups with the Pipe

正規表達式 r'Batman|Tina Fey' 會比對 'Batman' 或 'Tina Fey'
```{python}
heroRegex = re.compile (r'Batman|Tina Fey')
mo1 = heroRegex.search('Batman and Tina Fey.')
mo1.group()
```

想要比對'Batman', 'Batmobile', 'Batcopter',  'Batbat' 中任一個都符合,因為都以'Bat'開頭
所以只要指定一次前置文字即可,利用括號
```{python}
batRegex = re.compile(r'Bat(man|mobile|copter|bat)')
mo = batRegex.search('Batmobile lost a wheel')
mo.group()

mo.group(1)
```
####Optional Matching with the Question Mark
問號表示無論內容是否存在,正規表達式都會比對符合

?字元表示他前面括號的分組在這模式中是可選擇性的

?字元可看成 **這個問號前的分組比對符合1次或0次**都可以
```{python}
batRegex = re.compile(r'Bat(wo)?man')
mo1 = batRegex.search('The Adventures of Batman')
mo1.group()
mo2 = batRegex.search('The Adventures of Batwoman')
mo2.group()
```

用前面電話號碼來做說明,可在正規表達式中尋找含有區號和不含區號的電話號碼


```{python}
phoneRegex = re.compile(r'(\d\d\d-)?\d\d\d-\d\d\d\d')
mo1 = phoneRegex.search('My number is 415-555-4242')
mo1.group()
```

```{python}
mo2 = phoneRegex.search('My number is 555-4242')
mo2.group()
```
#### Matching Zero or More with the Star

**\* **字元可看成 **這個星號前的分組比對符合多次或0次**都可以
```{python}
batRegex = re.compile(r'Bat(wo)*man')
mo1 = batRegex.search('The Adventures of Batman')
mo1.group()


mo2 = batRegex.search('The Adventures of Batwoman')
mo2.group()


mo3 = batRegex.search('The Adventures of Batwowowowoman')
mo3.group()
```
#### Matching One or More with the Plus
**+**字元可看成 **這個+前的分組比對符合多次或1次**都可以


```{python}
batRegex = re.compile(r'Bat(wo)+man')
mo1 = batRegex.search('The Adventures of Batwoman')
mo1.group()


mo2 = batRegex.search('The Adventures of Batwowowowoman')
mo2.group()


mo3 = batRegex.search('The Adventures of Batman')
mo3 == None
```
####Matching Specific Repetitions with Curly Brackets(大括號)

(Ha){3} 與 (Ha)(Ha)(Ha)  表達意思相同

(Ha){3,5} 與 ((Ha)(Ha)(Ha))|((Ha)(Ha)(Ha)(Ha))|((Ha)(Ha)(Ha)(Ha)(Ha)) 表達意思相同

(Ha){3,}  表示比對符合至少3次以上
```{python}
haRegex = re.compile(r'(Ha){3}')
mo1 = haRegex.search('HaHaHa')
mo1.group()


mo2 = haRegex.search('Ha')
mo2 == None
```
#### Greedy and Nongreedy Matching
python 正規表達式預設是greedy版本,就是盡可能找到最長符合比對的字串

在大括弧後面加上一個問號,大括弧的non-greedy版本會盡可能找到最短符合比對的字串


```{python}
greedyHaRegex = re.compile(r'(Ha){3,5}')
mo1 = greedyHaRegex.search('HaHaHaHaHa')
mo1.group()

nongreedyHaRegex = re.compile(r'(Ha){3,5}?')
mo2 = nongreedyHaRegex.search('HaHaHaHaHa')
mo2.group()
```


#### The findall() Method

search()方法會返回一個match物件,此物件內含有尋找比對字串中**第一次**找到符合的文字

findall()方法則返回一組list,這組list為尋找比對字串中**所有**符合的文字內容
```{python}
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo = phoneNumRegex.search('Cell: 415-555-9999 Work: 212-555-0000')
mo.group()
```

```{python}
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d') # has no groups
phoneNumRegex.findall('Cell: 415-555-9999 Work: 212-555-0000')
```


如果有分組,那findall會返回一個多元組(list of tuples)的list,每個多元組代表一個比對符合的內容
```{python}
phoneNumRegex = re.compile(r'(\d\d\d)-(\d\d\d)-(\d\d\d\d)') # has groups
phoneNumRegex.findall('Cell: 415-555-9999 Work: 212-555-0000')
```
###Character Classes

字元分類      | 表示
--------------|------------------------
\\d           | 0-9的任何數字
\\D           | 除了0-9的任何數字
\\w           | 任何字母,數字或底線
\\W           | 除了字母,數字或底線以外的任何字元
\\s           | 空格,定位符號或換行符號
\\S           | 除了空格,定位符號或換行符號以外的任何字元

\\d is shorthand for the regular expression (0|1|2|3|4|5|6|7|8|9)

[0-5] is shorthand for the regular expression (0|1|2|3|4|5)
```{python}
xmasRegex = re.compile(r'\d+\s\w+')
xmasRegex.findall('12 drummers, 11 pipers, 10 lords, 9 ladies, 8 maids, 7 swans, 6 geese, 5 rings, 4 birds, 3 hens, 2 doves, 1 partridge')
```

####Making Your Own Character Classes
[a-zA-Z0-9]會比對找出所有小寫字母,大寫字母或數字

note: 在中括號內的普通正規表達式不會被解釋執行 

ex:[0-5.] 會比對找出0到5的數字和句點,我們不需要寫成 [0-5\.]
```{python}
vowelRegex = re.compile(r'[aeiouAEIOU]')
vowelRegex.findall('Robocop eats baby food. BABY FOOD.')

```
^ 可取得 比對找出不在這個字元分類以外的所有字元
```{python}
consonantRegex = re.compile(r'[^aeiouAEIOU]')
consonantRegex.findall('Robocop eats baby food. BABY FOOD.')
```

#### The ^ and $ Characters

r'^Hello' 是要比對找出符合'Hello'為起始的字串

```{python}
beginsWithHello = re.compile(r'^Hello')
beginsWithHello.search('Hello world!')
beginsWithHello.search('He said hello.') == None
```

r'\\d$' 是要比對找出符合以數字0到9為結尾的字串
```{python}
endsWithNumber = re.compile(r'\d$')
endsWithNumber.search('Your number is 42')
endsWithNumber.search('Your number is forty two.') == None
```


r'^\d+$' 是要比對找出至少一個符合以開頭到結尾都是數字0到9的字串
```{python}
wholeStringIsNum = re.compile(r'^\d+$')
wholeStringIsNum.search('1234567890')
wholeStringIsNum.search('12345xyz67890') == None
wholeStringIsNum.search('12 34567890') == None
```

#### The Wildcard Character 萬用字元.

. 子元是萬用字元,尋找除了換行符號的所有字元
```{python}
atRegex = re.compile(r'.at')
atRegex.findall('The cat in the hat sat on the flat mat.')

```

#### Matching Everything with Dot-Star 使用.*尋找所有字元
```{python}
nameRegex = re.compile(r'First Name: (.*) Last Name: (.*)')
mo = nameRegex.search('First Name: Al Last Name: Sweigart')
mo.group(1)
mo.group(2)
```

greedy and non-greedy

```{python}
nongreedyRegex = re.compile(r'<.*?>')
mo = nongreedyRegex.search('<To serve man> for dinner.>')
mo.group()


greedyRegex = re.compile(r'<.*>')
mo = greedyRegex.search('<To serve man> for dinner.>')
mo.group()
```

#### 比對所有字元,包括換行字元
```{python}
noNewlineRegex = re.compile('.*')
noNewlineRegex.search('Serve the public trust.\nProtect the innocent.\nUphold the law.').group()


newlineRegex = re.compile('.*', re.DOTALL)
newlineRegex.search('Serve the public trust.\nProtect the innocent.\nUphold the law.').group()
```

#### 比對時不區分大小寫

把re.I當作第2個引數傳入re.compile
```{python}
robocop = re.compile(r'robocop', re.I)
robocop.search('Robocop is part man, part machine, all cop.').group()
robocop.search('ROBOCOP protects the innocent.').group()
robocop.search('Al, why does your programming book talk about robocop so much?').group()
```

### 使用sub()方法取代字串
```{python}
namesRegex = re.compile(r'Agent \w+')
namesRegex.sub('CENSORED', 'Agent Alice gave the secret documents to Agent Bob.')
```

### 正規表達式中使用注釋
不+注釋:複雜的正規表達式會非常難以閱讀
phoneRegex = re.compile(r'((\\d{3}|\\(\d{3}\\))?(\\s|-|\\.)?\\d{3}(\\s|-|\\.)\\d{4}

(\\s*(ext|x|ext.)\\s*\\d{2,5})?)')

增加注釋:使用re.VERBOSE當作第2個引數傳入re.compile中

    phoneRegex = re.compile(r'''(
        (\d{3}|\(\d{3}\))?              # area code
        (\s|-|\.)?                      # separator
        \d{3}                           # first 3 digits
        (\s|-|\.)                      # separator
        \d{4}                           # last 4 digits
        (\s*(ext|x|ext.)\s*\d{2,5})?  # extension
         )''', re.VERBOSE)
         
### 組合使用 re.IGNORECASE, re.DOTALL, and re.VERBOSE

想要使用re.VERBOSE增加注釋,還希望用re.IGNORECASE忽略大小寫,但是re.compile只接受一個值當作第二個引數

想解決可使用(|)把re.IGNORECASE, re.DOTALL, and re.VERBOSE組合起來

ex:早要不區分大小寫,且比對尋找時包含換行符號,且增加注釋,可以這樣寫:
```{python}

someRegexValue = re.compile('foo', re.IGNORECASE | re.DOTALL | re.VERBOSE)
```

